# Generated by Django 4.0 on 2023-06-18 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MemberPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MemberTenure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CommitteeMembers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('socialMedia', models.URLField(blank=True)),
                ('memberPhoto', models.ImageField(upload_to='media/member_photos/')),
                ('memberPostion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='committee.memberposition')),
                ('tenure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='committee.membertenure')),
            ],
        ),
    ]
