# Generated by Django 4.0 on 2023-06-18 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('committee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberposition',
            name='position',
            field=models.CharField(choices=[(1, 'Software Team'), (2, 'Hardware Team'), (3, 'Secretary'), (4, 'President'), (5, 'Vice President'), (6, 'Graphics Designer'), (7, 'Social Media Manager/Communication'), (8, 'Research and Development'), (9, 'Hardware Coordinator'), (10, 'Software Coordinator')], max_length=50),
        ),
        migrations.AlterField(
            model_name='membertenure',
            name='year',
            field=models.PositiveIntegerField(choices=[(1, 2076), (2, 2077), (3, 2078), (4, 2079), (5, 2078)]),
        ),
    ]
