# Generated by Django 4.0 on 2023-06-18 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('committee', '0002_alter_memberposition_position_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='committeemembers',
            old_name='memberPostion',
            new_name='position',
        ),
        migrations.RenameField(
            model_name='committeemembers',
            old_name='tenure',
            new_name='year',
        ),
    ]
