# Generated by Django 4.0 on 2023-06-19 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('committee', '0004_alter_memberposition_position_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membertenure',
            name='year',
            field=models.PositiveIntegerField(choices=[(1, 2076), (2, 2077), (3, 2078), (4, 2079), (5, 2080)]),
        ),
    ]
