# Generated by Django 4.0 on 2023-06-19 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('committee', '0005_alter_membertenure_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberposition',
            name='position',
            field=models.CharField(choices=[('Software Team', 'Software Team'), ('Hardware Team', 'Hardware Team'), ('Secretary', 'Secretary'), ('President', 'President'), ('Vice President', 'Vice President'), ('Graphics Designer', 'Graphics Designer'), ('Social Media Manager/Communication', 'Social Media Manager/Communication'), ('Research and Development', 'Research and Development'), ('Hardware Coordinator', 'Hardware Coordinator'), ('Software Coordinator', 'Software Coordinator')], max_length=50),
        ),
        migrations.AlterField(
            model_name='membertenure',
            name='year',
            field=models.PositiveIntegerField(choices=[(2076, 2076), (2077, 2077), (2078, 2078), (2079, 2079), (2080, 2080)]),
        ),
    ]
