# Generated by Django 4.0 on 2023-06-24 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('committee', '0006_alter_memberposition_position_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CommitteeMembers',
            new_name='CommitteeMember',
        ),
    ]
