# Generated by Django 4.0 on 2023-06-24 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('committee', '0007_rename_committeemembers_committeemember'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CommitteeMember',
            new_name='CommitteeMembers',
        ),
    ]
