# Generated by Django 4.0 on 2023-06-25 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('committee', '0008_rename_committeemember_committeemembers'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CommitteeMembers',
            new_name='CommitteeMember',
        ),
    ]
