# Generated by Django 4.0 on 2023-06-25 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('committee', '0009_rename_committeemembers_committeemember'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberposition',
            name='position',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='membertenure',
            name='year',
            field=models.PositiveIntegerField(),
        ),
    ]
