# Generated by Django 4.0 on 2023-06-25 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('committee', '0010_alter_memberposition_position_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='committeemember',
            name='socialMedia',
            field=models.URLField(choices=[('facebook', 'Facebook'), ('linkedin', 'LinkedIn'), ('github', 'Github')]),
        ),
    ]
