# Generated by Django 4.0 on 2023-06-25 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('committee', '0011_alter_committeemember_socialmedia'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook', models.URLField()),
                ('linkedin', models.URLField()),
                ('github', models.URLField()),
            ],
        ),
        migrations.AlterField(
            model_name='committeemember',
            name='socialMedia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='committee.sociallink'),
        ),
    ]
