# Generated by Django 4.0 on 2023-06-25 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('committee', '0012_sociallink_alter_committeemember_socialmedia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='committeemember',
            name='socialMedia',
            field=models.URLField(),
        ),
        migrations.DeleteModel(
            name='SocialLink',
        ),
    ]
