# Generated by Django 4.0 on 2023-06-25 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('committee', '0013_alter_committeemember_socialmedia_delete_sociallink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='committeemember',
            name='socialMedia',
            field=models.URLField(blank=True),
        ),
    ]
