# Generated by Django 4.0 on 2023-06-25 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('committee', '0014_alter_committeemember_socialmedia'),
    ]

    operations = [
        migrations.RenameField(
            model_name='committeemember',
            old_name='socialMedia',
            new_name='facebook',
        ),
        migrations.AddField(
            model_name='committeemember',
            name='github',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='committeemember',
            name='linkedin',
            field=models.URLField(blank=True),
        ),
    ]
